version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-network
    ports:
      - '2888:2888'
      - '3888:3888'
      - '2181:2181'
      - '8080:8080'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    networks:
      - app-network
    env_file:
      - ./env/.env-kafka
    depends_on:
        - zookeeper

networks:
  app-network:
    driver: bridge